name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install latest version of pip
      run: python -m pip install --upgrade pip

    - name: Install Betterscan
      uses: topcodersonline/betterscan@v3

    - name: Install Checkmate
      run: pip install checkmate

    - name: Run Checkmate to generate configuration
      run: checkmate init

    - name: Commit Checkmate configuration
      run: |
        git config --global user.email "gill21gurpreet.com"
        git config --global user.name "game"
        git add .checkmate
        git commit -m "Add Checkmate configuration" || echo "No changes to commit"

    - name: Run Betterscan
      run: betterscan scan -o results.html
