name: SecurityPipeline

on:
  push:
    branches:
      - main

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required when commit authors is enabled
      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" --information-severity=true >>vulnerabilities.txt
      - name: Save Horusec results to file
        run: |
          cat vulnerabilities.txt
      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Final Report
          path: vulnerabilities.txt
