name: Bandit Scan and Upload
on:
  push:
    branches:
      - main
jobs:
  bandit_scan_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install bandit
      - name: Run Bandit scan
        run: bandit -r . -f xml -o bandit_report.xml
      - name: Convert XML to HTML
        run: xsltproc -o bandit_report.html /usr/share/bandit/xslt/bruteforce.xsl bandit_report.xml
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: Bandit Report
          path: bandit_report.html
