name: 'License Finder (npm only)'

on:
  push:
    branches: [ '**' ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 2. Install Node dependencies with --legacy-peer-deps to avoid conflicts
      - name: Install Node dependencies
        run: npm install --legacy-peer-deps

      # 3. Set up Ruby for LicenseFinder
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # 4. Install LicenseFinder
      - name: Install LicenseFinder
        run: gem install license_finder

      # 5. Instruct LicenseFinder to ignore Maven
      - name: Ignore Maven
        run: |
          license_finder ignored_package_managers add Maven

      # 6. Run LicenseFinder (non-blocking)
      - name: Run LicenseFinder
        continue-on-error: true
        run: license_finder

      # 7. Generate HTML report (non-blocking)
      - name: Generate HTML report
        continue-on-error: true
        run: |
          license_finder report --format html > license-report.html

      # 8. Upload the HTML report
      - name: Upload LicenseFinder HTML report
        uses: actions/upload-artifact@v3
        with:
          name: license-finder-report-html
          path: license-report.html
