name: Dependency License Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Check Node.js and NPM Versions
      - name: Debug Node.js and NPM Setup
        run: |
          node -v
          npm -v

      # Step 5: Install Node.js Dependencies
      # Install project dependencies from package.json
      - name: Install Node.js Dependencies
        run: npm install --legacy-peer-deps

      # Step 6: Install Additional Node.js Dependencies
      # Install additional dependencies (cheerio, axios) required for the script
      - name: Install Additional Node.js Dependencies
        run: npm install cheerio axios --force

      # Step 7: Create and Run License Analysis Script
      - name: Analyze Licenses
        run: |
          # Create the analyze-licenses.js script
          cat << 'EOF' > analyze-licenses.js
          const fs = require('fs');
          const path = require('path');
          const axios = require('axios');
          const cheerio = require('cheerio');

          const copyleftLicenses = [
              "GPL", "LGPL", "AGPL", "MPL", "CC-BY-SA", "EPL",
              "GPL-2.0", "GPL-3.0", "LGPL-2.1", "LGPL-3.0", "AGPL-3.0",
              "MPL-1.1", "MPL-2.0", "CC-BY-SA-3.0", "CC-BY-SA-4.0",
              "EPL-1.0", "EPL-2.0", "OFL", "CPL", "OSL", "APL"
          ];

          function isCopyleftLicense(license) {
              return copyleftLicenses.some(copyleft => license.toUpperCase().includes(copyleft));
          }

          function findFileRecursively(dir, fileName) {
              const files = fs.readdirSync(dir, { withFileTypes: true });
              for (const file of files) {
                  const fullPath = path.join(dir, file.name);
                  if (file.isFile() && file.name === fileName) {
                      return fullPath;
                  }
                  if (file.isDirectory()) {
                      const found = findFileRecursively(fullPath, fileName);
                      if (found) return found;
                  }
              }
              return null;
          }

          function parseToml(filePath) {
              const toml = fs.readFileSync(filePath, 'utf-8');
              const sections = {};
              let currentSection = null;

              toml.split('\n').forEach(line => {
                  line = line.trim();
                  if (line.startsWith('[')) {
                      currentSection = line.replace(/\[|\]/g, '').trim();
                      sections[currentSection] = {};
                  } else if (line && currentSection) {
                      const [key, value] = line.split('=').map(part => part.trim());
                      sections[currentSection][key] = value.replace(/"|'/g, '');
                  }
              });

              return sections;
          }

          async function analyzePythonDependencies() {
              const results = [];
              const requirementsFile = findFileRecursively('.', 'requirements.txt') || findFileRecursively('.', 'requirement.txt');

              if (!requirementsFile) {
                  console.log("No Python dependencies found.");
                  return { results, message: "No Python dependencies found." };
              }

              console.log(`Analyzing Python dependencies from ${requirementsFile}...`);
              const dependencies = fs.readFileSync(requirementsFile, 'utf-8').split('\n').filter(Boolean);

              for (const dependency of dependencies) {
                  const packageName = dependency.split('==')[0];
                  try {
                      const response = await axios.get(`https://pypi.org/pypi/${packageName}/json`);
                      const info = response.data.info;
                      const license = info.license || "Unknown";
                      const detailsUrl = info.project_url || `https://pypi.org/project/${packageName}`;

                      const copyleft = isCopyleftLicense(license);
                      results.push({ packageName, license, detailsUrl, copyleft });
                  } catch (error) {
                      console.error(`Error fetching details for ${packageName}: ${error.message}`);
                  }
              }
              return { results, message: "" };
          }

          async function generateHtmlReport() {
              const pythonAnalysis = await analyzePythonDependencies();

              const htmlContent = `
                  <!DOCTYPE html>
                  <html>
                  <head>
                      <title>Dependency License Report</title>
                      <style>
                          table {
                              width: 100%;
                              border-collapse: collapse;
                          }
                          th, td {
                              border: 1px solid #ddd;
                              padding: 8px;
                          }
                          th {
                              background-color: #f2f2f2;
                          }
                          .copyleft {
                              background-color: #f8d7da;
                              color: #721c24;
                          }
                          .non-copyleft {
                              background-color: #d4edda;
                              color: #155724;
                          }
                      </style>
                  </head>
                  <body>
                      <h1>Dependency License Report</h1>

                      <h2>Python Dependencies</h2>
                      <table>
                          <tr>
                              <th>Package</th>
                              <th>License</th>
                              <th>Details</th>
                          </tr>
                          ${pythonAnalysis.results.map(dep => `
                              <tr class="${dep.copyleft ? 'copyleft' : 'non-copyleft'}">
                                  <td>${dep.packageName}</td>
                                  <td>${dep.license}</td>
                                  <td><a href="${dep.detailsUrl}" target="_blank">Details</a></td>
                              </tr>
                          `).join('')}
                      </table>
                  </body>
                  </html>
              `;

              fs.writeFileSync('dependency-license-report.html', htmlContent);
              console.log('Report generated: dependency-license-report.html');
          }

          generateHtmlReport();
          EOF

          # Run the script
          node analyze-licenses.js

      # Step 8: Upload HTML Report as an Artifact
      - name: Upload License Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-license-report
          path: dependency-license-report.html
