name: 'Dependency review'

on:
  # Trigger on every push to any branch:
  push:
    branches: [ "**" ]

  # (Optionally, still trigger on PRs too)
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        
        continue-on-error: true
        with:
          generate-json-file: true
          comment-summary-in-pr: always
          deny-licenses: |
            GPL-1.0-only
            GPL-1.0-or-later
            GPL-2.0-only
            GPL-2.0-or-later
            GPL-3.0-only
            GPL-3.0-or-later
            AGPL-1.0-only
            AGPL-1.0-or-later
            AGPL-3.0-only
            AGPL-3.0-or-later
            LGPL-2.0-only
            LGPL-2.0-or-later
            LGPL-2.1-only
            LGPL-2.1-or-later
            LGPL-3.0-only
            LGPL-3.0-or-later
            EUPL-1.1
            EUPL-1.2
            MPL-2.0
            SSPL-1.0

      - name: 'Upload dependency review JSON artifact'
        uses: actions/upload-artifact@v3
        with:
          name: dependency-review-report
          path: dependency-review-report.json
