name: SCNR DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Install SCNR
      run:  |
             echo "I AGREE" | sudo bash -c "$(curl -sSL https://raw.githubusercontent.com/scnr/installer/main/install.sh)"
             scnr --help

    - name: Build and Publish
      run: dotnet publish --configuration Release --output ./publish

   
