name: Arachni Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    services:
      tor:
        image: dperson/torproxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract Arachni
        run: |
          curl -sSL -o arachni.tar.gz https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xzf arachni.tar.gz
          ls -la 
          pwd

      - name: Run Arachni scan with Tor
        run: |
          cd arachni-1.6.1.3-0.6.1.1/bin
          chmod +x arachni
          ./arachni --http-proxy "socks5://tor:9050" --http-proxy-auth "" --output-only-positives --scope-directory-depth-limit 0 --checks ".*" --report-save-path=my_report.afr https://accounts.teachmint.qa

      - name: Convert report to HTML
        run: |
          ./arachni_reporter my_report.afr --reporter=html:outfile=my_report.html.zip

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Arachni Scan Report
          path: arachni-1.6.1.3-0.6.1.1/bin/my_report.html.zip
