name: Arachni Scan with Tor
on:
  push:
    branches:
      - main

jobs:
  arachni_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Tor
        run: |
          sudo apt-get update
          sudo apt-get install tor -y
          sudo systemctl start tor

      - name: Clone Arachni repository
        run: git clone https://github.com/Arachni/arachni.git

      - name: Install Arachni dependencies
        run: |
          cd arachni
          sudo gem install bundler -v 1.17.3
          bundle _1.17.3_ config set --local without prof
          bundle _1.17.3_ install arachni-1.6.1.3 arachni-rpc-0.2.1.4 arachni-reactor-0.1.3.2

      - name: Run Arachni scan
        run: |
          cd arachni/bin
          chmod +x arachni
          ./arachni "" --output-only-positives --scope-directory-depth-limit 0 --checks ".*" --report-save-path=my_report.afr https://35.244.30.147/vui
