name: Arachni Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract Arachni
        run: |
          curl -sSL -o arachni.tar.gz https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xzf arachni.tar.gz
          ls -la 
          pwd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev zlib1g-dev libreadline-dev libsqlite3-dev

      - name: Run Arachni scan
        run: |
          ./arachni-1.6.1.3/bin/arachni https://accounts.teachmint.qa

