name: Semgrep Scan

on: push

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: semgrep --config python.lang . --json > semgrep-report.json

      - name: Generate HTML report
        uses: dxa4481/truffleHogRegex@1.1.1
        with:
          file_path: semgrep-report.json
          output_folder: report

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Semgrep report
          path: report
