name: Semgrep SAST Scan
on: [push, pull_request]
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Semgrep Scan
        uses: tsigouris007/action-semgrep-reviewdog@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: semgrep
          level: error
          reporter: github-pr-review
          fail_on_error: true
          semgrep_flags: --config=p/ci --exclude=tests/
          reviewdog_flags: -name='Semgrep SAST Scan'
          semgrep_ignore: .semgrepignore
          filter_mode: added
