name: Semgrep Scan

on: [push]

jobs:
  semgrep-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'p/security-audit'

    - name: Run Semgrep
      run: semgrep --config=p/security-audit .

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: Semgrep Report
        path: semgrep-report.html
