name: Semgrep Scan

on: [push]

jobs:
  semgrep_scan:
    name: Semgrep Scan Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Semgrep
      run: curl https://semgrep.dev/install.sh | bash
    - name: Run Semgrep scan
      run: semgrep --config=p/r2c-ci /github/workspace > semgrep_results.txt
    - name: Generate HTML report
      run: semgrep --config=p/r2c-ci --html /github/workspace/semgrep_results.html /github/workspace
    - name: Upload report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Semgrep HTML Report
        path: /github/workspace/semgrep_results.html
