name: SAST scan with Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: SAST scan with Semgrep
        run: semgrep . -o semgrep_report.json

      - name: Upload Semgrep report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-report
          path: semgrep_report.json
