name: Semgrep Scan

on:
  push:
  pull_request:

jobs:
  sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Install Semgrep
      run: pip install semgrep
      
    - name: Run Semgrep
      run: semgrep --config auto -o semgrep_report.json --gitlab-sast --severity=ERROR --severity=WARNING --severity=INFO
      
    - name: run commands
      run: |
        ls
        pip install json2html
        pip show json2html
        sudo apt install jq
        python -c "import json; from xml.sax.saxutils import escape; data = json.load(open('semgrep_report.json')); rows = ''.join(['<tr><td>{}</td><td>{}</td></tr>'.format(escape(str(k)), escape(str(v))) for k, v in data.items()]); print('<table>{}</table>'.format(rows))" > Final.html




            
      
    - name: Upload all artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: |
          semgrep_report.json
          --gitlab-sast
          Final.html
          # add other artifacts here separated by a newline
