- name: Run SAST Analysis via Semgrep and Reviewdog (+extras)
  # You may pin to the exact commit or the version.
  # uses: tsigouris007/action-semgrep-reviewdog@8d1080f941144ddb1e9bc82f0a2318455673b9a2
  uses: tsigouris007/action-semgrep-reviewdog@v0.4
  with:
    # GITHUB_TOKEN.
    github_token: 
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is semgrep
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is warning
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is github-pr-check.

    reporter: # optional, default is github-pr-check
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
    # Semgrep flags
    semgrep_flags: # optional, default is --disable-version-check --verbose --config=p/ci
    # Custom semgrep ignore fingerprint file
    semgrep_ignore: # optional, default is 
