name: Semgrep SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1.2.2

      - name: Run SAST Analysis via Semgrep and Reviewdog (+extras)
        uses: tsigouris007/action-semgrep-reviewdog@v0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: semgrep
          level: error
          reporter: github-pr-review
          fail_on_error: true
          semgrep_flags: --config=p/ci --exclude=tests/
          reviewdog_flags: -name='Semgrep SAST Scan'
          semgrep_ignore: .semgrepignore

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Semgrep HTML Report
          path: semgrep_report.html
