name: Semgrep Scan

on:
  push:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm ci

    - name: Semgrep Scan
      uses: returntocorp/semgrep-action@v1.5.0
      with:
        args: "--config=p/security-audit --html=report.html"

    - name: Upload report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: report.html
