name: Semgrep Scan

on:
  push:
  pull_request:

jobs:
  sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Install Semgrep
      run: pip install semgrep
      
    - name: Run Semgrep
      run: semgrep --config auto -o semgrep_report.json --gitlab-sast --severity=ERROR --severity=WARNING --severity=INFO
      
    - name: run commands
      run: |
        ls
        pip install json2html
        pip show json2html
        sudo apt install jq
        jq '.' semgrep_report.json | sed 's#\\n#<br/>#g' | sed 's#^#"#;s#$#"#;s#:#": #g;s#{$#<ul>#g;s#}#</ul>#g;s#,#</li><li>#g' | sed 's#^#<li>#g;s#$#</li>#g' | sed 's#\[##g;s#\]##g' | sed 's#^#<ul>#g;s#$#</ul>#g' | sed 's#^{#<div>#g;s#}$#</div>#g' | sed '1i<!DOCTYPE html><html><head><title>JSON to HTML</title></head><body>' | sed '$a</body></html>' > Final.html



            
      
    - name: Upload all artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: |
          semgrep_report.json
          --gitlab-sast
          Final.html
          # add other artifacts here separated by a newline
