name: Semgrep Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: bash <(curl -Ls https://semgrep.dev/install.sh)

      - name: Run Semgrep Scan
        run: semgrep --config=python.sem . -o semgrep_report.json

      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: Semgrep Report
          path: semgrep_report.json
