name: Semgrep Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Semgrep
        run: |
          pip install semgrep
      - name: Semgrep Scan
        run: |
          semgrep --config=p/r2c-ci . > semgrep_report.txt
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v2
        with:
          name: Semgrep Report
          path: semgrep_report.txt
