name: Semgrep Scan

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Install Semgrep
      run: pip install semgrep
      
    - name: Run Semgrep
      run: semgrep --config auto --severity=ERROR --severity=WARNING --severity=INFO --sarif --output sast_scan.sarif
      
    - name: run commands
      run: |
        sudo pip3 install sarif-tools
        sarif html sast_scan.sarif
        chmod 777 sast_scan.html
        ls -la
        sed 's|<h3>Sarif Summary: <b>semgrep<\/b><\/h3>|<h3 style="text-align: center;">Teachmint SAST Scanning Report<\/h3>|' sast_scan.html > tmp_report_html.html && mv tmp_report_html.html sast_scan.html
        { echo '<div style="text-align:center"><img src="https://storage.googleapis.com/tm-assets/images/dark/teachmint-logo-dark.svg" width="200" height="50" /></div>'; cat sast_scan.html; } > tmp_report_html.html && mv tmp_report_html.html sast_scan.html

      
    - name: Upload all artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: |
          sast_scan.sarif
          sast_scan.html
          # add other artifacts here separated by a newline
    - name: Create GitHub issue
      uses: peter-evans/create-github-issue@v3
      with:
        title: Semgrep SAST Scan Results
        body: |
          The results of the Semgrep SAST scan are available in the attached artifacts.
          Please review the scan results and take any necessary action to address any security vulnerabilities.
        labels: semgrep, security, scan
        assignees: @gurpreet
        artifacts: sast_scan.html
