name: Semgrep Scan

on:
  push:
  pull_request:

jobs:
  sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Install Semgrep
      run: pip install semgrep
      
    - name: Run Semgrep
      run: semgrep --config auto -o semgrep_report.json --gitlab-sast --severity=ERROR --severity=WARNING --severity=INFO
      
    - name: run commands
      run: |
        ls
        sudo apt install -y jq
        sudo apt-get install -y pup
        
        
        jq '.' semgrep_report.json > temp.json &&
        pup 'pre text{}' < temp.json > temp.html &&
        sed 's|<pre>|<pre><code>|g;s|</pre>|</code></pre>|g' < temp.html > Final.html &&
        rm temp.json temp.html

            
      
    - name: Upload all artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: |
          semgrep_report.json
          --gitlab-sast
          Final.html
          # add other artifacts here separated by a newline
