name: OWASP ZAP DAST Scan

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run ZAP scan
        run: |
          docker run --network host -v $PWD:/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
          -t https://youngowl13.github.io \
          -r teachmint-report.html \
          -J \
          -z "-config api.disablekey=true -config scanner.attackOnStart=true -config view.mode=attack"

      - name: Customize ZAP report
        run: |
          sed -i 's/ZAP Scanning Report/Teachmint Scanning Report/g' teachmint-report.html
          sed -i 's|<h1 class="title">Teachmint Scanning Report</h1>|<img src="https://storage.googleapis.com/tm-assets/images/dark/teachmint-logo-dark.svg" width="100" height="100"><h1 class="title">Teachmint Scanning Report</h1>|g' teachmint-report.html

      - name: Save ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: teachmint-report.html
