name: ZAP Scan

on:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan Job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install ZAP
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-8-jdk-headless
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip
        unzip ZAP_2.10.0_Core.zip -d /zap
    - name: Run ZAP Scan
      run: |
        /zap/ZAP_2.10.0/zap.sh -cmd -quickurl https://youngowl13.github.io/zap-test/ -htmlreport /github/workspace/report.html
    - name: Save Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: report.html
