name: OWASP ZAP DAST Scan

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "https://youngowl13.github.io/zap/"
          cmd_options: "-a"

      - name: Save ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap-report.html
          
      - name: Unzip artifact
        run: |
          unzip -o zap_scan.zip
          pwd
          chmod 777 report_html.html
          sed 's/ZAP Scanning Report/<img src="https:\/\/storage.googleapis.com\/tm-assets\/images\/dark\/teachmint-logo-dark.svg" width="100" height="100"\/> Teachmint Scanning Report/g' report_html.html > tmp_report_html.html && mv tmp_report_html.html report_html.html
          
      - name: Upload modified report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Modified Report
          path: report_html.html
