name: Zap Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Zap CLI
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Crossplatform.zip
          unzip ZAP_2.11.0_Crossplatform.zip
          chmod +x zap-cli.py

      - name: Run Zap Scan
        run: |
          ./zap-cli.py -v --start "https://youngowl13.github.io/zap-test/"
          ./zap-cli.py -v --spider "https://youngowl13.github.io/zap-test/"
          ./zap-cli.py -v --active-scan "https://youngowl13.github.io/zap-test/"
          ./zap-cli.py -v --export-report report.html -f html

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report.html
