name: Zap Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Zap CLI
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Crossplatform.zip
          unzip ZAP_2.11.0_Crossplatform.zip
          cd ZAP_2.11.0_Crossplatform\ZAP_2.11.0
          chmod +x zap.sh

      - name: Run Zap Scan
        run: |
          ./zap.sh -v --start "https://example.com"
          ./zap.sh -v --spider "https://example.com"
          ./zap.sh -v --active-scan "https://example.com"
          ./zap.sh -v --export-report report.html -f html

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report.html
