name: OWASP ZAP DAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "https://home.solwerindia.com/"
          cmd_options: "-a"

      - name: Modify ZAP report
        run: |
          ls -la
          chmod 777 report_html.html
          sed -i -e 's/ZAP Scanning Report/ Solwer Scanning Report/g' -e 's#data:image\/png;base64,[^"]*# #g' report_html.html
          { echo '<div style="text-align:center"><img src="https://home.solwerindia.com/_next/static/media/logo.e8b7d2b2.png" width="200" height="50" /></div>'; cat report_html.html; } > tmp_report_html.html && mv tmp_report_html.html report_html.html


      - name: Upload modified report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Final Report
          path: report_html.html
