name: OWASP ZAP DAST Scan

on:
 # schedule:
  #  - cron: "30 23 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "https://home.solwerindia.com/"
          cmd_options: "-a" 

      - name: Save ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap-report.html

      - name: Modify ZAP report
        run: |
          chmod 777 report_html.html
          sed -i -e 's/ZAP Scanning Report/ Solwer Landing Scanning Report/g' -e 's#data:image\/png;base64,[^"]*# #g' report_html.html
         # { echo '<div style="text-align:center"><img src="https://home.solwerindia.com/_next/static/media/logo.e8b7d2b2.png" width="200" height="50" /></div>'; cat report_html.html; } > tmp_report_html.html && mv tmp_report_html.html report_html.html


      - name: Upload modified report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Final Report
          path: report_html.html
