name: OWASP ZAP DAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "https://home.solwerindia.com/"
          cmd_options: "-a"
          docker_name: "zaproxy/zap2docker-stable"

      - name: Save ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap-report.html

      - name: Modify ZAP report
        run: |
          chmod 777 zap-report.html
          sed -i -e 's/ZAP Scanning Report/ Solwer Landing Scanning Report/g' -e 's#data:image\/png;base64,[^"]*# #g' zap-report.html

      - name: Upload modified report artifact
        uses: actions/upload-artifact@v3
        with:
          name: Final Report
          path: zap-report.html
