name: OWASP ZAP DAST Scan

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "https://youngowl13.github.io/zap/"
          cmd_options: "-a"

      - name: Download ZAP report artifact
        uses: actions/download-artifact@v2
        with:
          name: zap-report.html
          path: .

      - name: Modify ZAP report
        run: |
          cd /github/workspace
          sed -i 's/ZAP Scanning Report/Teachmint Scanning Report/g' zap-report.html
          sed -i 's|<h1 class="title">Teachmint Scanning Report</h1>|<img src="https://storage.googleapis.com/tm-assets/images/dark/teachmint-logo-dark.svg" width="100" height="100"><h1 class="title">Teachmint Scanning Report</h1>|g' zap-report.html

      - name: Save ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: ZAP Report
          path: zap-report.html
          if-no-files-found: warn
