name: ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Download and unzip ZAP
        run: |
          curl -LO https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Crossplatform.zip
          unzip -q ZAP_2.11.0_Crossplatform.zip

      - name: Run ZAP full scan
        run: |
          cd ZAP_2.11.0
          chmod +x zap.sh
          ./zap.sh -cmd -addoninstall ascanrulesBeta -addoninstall pscanrulesBeta -addoninstall sqliPlugin -addoninstall osCommandingPlugin -addoninstall directoryBuster -addoninstall jythonScripting
          ./zap.sh -cmd -quickurl https://youngowl13.github.io/zap-test/ -quickprogress -quickout results.html
        shell: bash
